### ISSUE TITLE
gr "" doesn't exit correctly

### ISSUE THREAD

**Issue by blakemcbride** [adamyg/grief#71]
Greetings,

If I run `gr`, type some text, and then exist with `alt-x`, gr asks me if I want to exit without saving the unsaved text.  However, if I type `gr ""` it does not.  Why?

**Comment by adamyg** [comment]
empty argument, no effect

**Comment by blakemcbride** [comment]
Sorry, I do not understand your response.  To be a little more clear, there are three steps as follows:

```
# gr ""
abcde
alt-x
```

Grief does not ask me if I want to exit without saving the unsaved text. However, if I type `gr` without the  `""` it does. Why?

**Comment by adamyg** [comment]
``gr ""``, is equivalent is running ``gr`` without arguments.

The outcome be shall dependent on the ```.grinit``` environment. If restore is enabled, the previous open file shall be reopened, otherwise the default "newfile" shall be opened/created.  Testing the second case and a simple edit, result was:

![image](https://github.com/adamyg/grief/assets/42717014/9bcdfb7a-ec67-416e-a11f-00b90899debd)

**Comment by blakemcbride** [comment]
See the video at [https://blakemcbride.us/files/grief.mkv](https://blakemcbride.us/files/grief.mkv)

**Comment by adamyg** [comment]
``gr`` is opening ``newfile``, whereas ```gr ""``` is ``\*scratch\*``.

Scratch refers to the internal temporary/system-buffer aka clip-board, which wont ever be saved since its a system buffer.

Question is why, this condition is generally due to a corrupt save/restore image; restore failed with scratch being the only available buffer attachable to the window. Delete the local ```.grstate``` file if one is present.

**Comment by adamyg** [comment]
opendir
